### ISSUE TITLE
Getting Started example / Noob docs?

### ISSUE THREAD

**Issue by janwirth** [GlobalWebIndex/elm-plural-rules#4]
I have trouble getting started.
- Where do the rules come from?
- Why are the several 'pluralize' functions for each locale but no rules exposed for that locale package.
- Why do I need to inject rules at all for a specific language at all?

**Comment by Janiczek** [comment]
Hello @FranzSkuffka!

So, each language has its own ways of pluralizing words and we've opted to let you "grow your own dictionary" based on words you're using in your app, because:
* it would be impractical for the package to contain a whole dictionary in that given language,
* and I believe it would be impossible / *very* impractical to try to implement that behaviour with some kind of function. This is not a NLP package :)

So you're supposed to make your own dictionary of `Rules` and add words into it as you start using them in the app. _(This answers "where do the rules come from" - you'll supply them.)_ You'll be telling the computer what to do, as you the human are a better expert at human languages than the computer will ever be. With some words you can get by using the default rule (adding `s` for plurals in English), but some languages don't have even that. For example, my native language -- Czech -- has:
* 1 muž -> 2 muži -> 5 mužů
* 1 ovce -> 2 ovce -> 5 ovcí
* 1 skála -> 2 skály -> 5 skal
* 1 sněhulák -> 2 sněhuláci -> 5 sněhuláků

etc. - many different rules, and also differing based on the count. Hence why [English module has a default pluralization rule](https://github.com/GlobalWebIndex/elm-plural-rules/blob/master/src/PluralRules/En.elm#L52-L54) and [Czech doesn't](https://github.com/GlobalWebIndex/elm-plural-rules/blob/master/src/PluralRules/Cz.elm#L54-L56).

See the example here for intended usage: https://github.com/GlobalWebIndex/elm-plural-rules/tree/master/examples

The idea is that you're creating your own `Pluralize` module which contains your dictionary and a helper function that uses it (so that you don't have to reference it all the time.)

You'd naturally start just with
```elm
rules : Rules
rules =
    PluralRules.fromList []
```
Then you'd start using it, say for an alert. You're supposed to show messages like:
> :warning: 4 problems found: 3 viruses and 1 trojan
> :warning: 1 problem found: 1 virus and 0 trojans
> :warning: 0 problems found: 0 viruses and 0 trojans

So your `view` code would look like:
```elm
viewAlert : { virusCount : Int, trojanCount : Int }
viewAlert {virusCount, trojanCount } =
  let
    totalCount =
      virusCount + trojanCount

    text =
      ":warning: "
        ++ String.fromInt totalCount
        ++ " "
        ++ Pluralize.pluralize totalCount "problem"
        ++ " found: "
        ++ String.fromInt virusCount
        ++ " "
        ++ Pluralize.pluralize virusCount "virus"
        ++ " and "
        ++ String.fromInt trojanCount
        ++ " "
        ++ Pluralize.pluralize trojanCount "trojan"
  in
  Html.text text
```
Which, with empty English ruleset, will activate the "add `-s` suffix" behaviour for any count that's not `1`:
> :warning: 0 problems found: 0 viruss and 0 trojans
> :warning: 1 problem found: 1 virus and 0 trojans
> :warning: 1 problem found: 0 viruss and 1 trojan

Which doesn't behave as you'd want for `virus`.
Indeed, the plural of `virus` is `viruses`!
So you add a rule to your `Pluralize.rules`:
```elm
rules : Rules
rules =
    PluralRules.fromList
        [ ( "virus"
          , [ ( One, "virus" )
            , ( Other, "viruses" )
            ]
          )
        ]
```
And now you're getting:
> :warning: 0 problems found: 0 viruses and 0 trojans
> :warning: 1 problem found: 1 virus and 0 trojans
> :warning: 1 problem found: 0 viruses and 1 trojan

The other two words don't have to be added to the ruleset because they behave just fine with the "default English plural behaviour". So you're only adding words to the ruleset if they are irregular (when they disagree with the default behaviour), if that makes sense.

Sorry for the wall of text. If I didn't answer your questions properly please let's iterate on this :)
Also, I'll be glad for suggestions about how to make README / doc comments /... clearer.

**Comment by janwirth** [comment]
Thank you!
