### ISSUE TITLE
update any-dict

### ISSUE THREAD

**Issue by turboMaCk** [GlobalWebIndex/elm-plural-rules#9]
Hello. I was forced to release new major version of any-dict. There are no significant changes impacting this package, only types of single function are now relaxed. Anyway since this is change in existing public API it has to be major version bump.

This means all down stream libraries should update to the newer version of the any-dict library.

**Comment by kraklin** [comment]
Seems like this issue is resolved with commit [6d53259](https://github.com/GlobalWebIndex/elm-plural-rules/commit/6d53259a2ee8c649417fc73ff3b66084b27ac84a) right @Forensor ?

It just seems the tests are failing here on the old version of Node. I think it might be good to update the version that is used in the workflow to something more up to date
